version: "3"

services:
  vk_poster:
    restart: always
    build: vk_poster/
    depends_on:
      - web_service
      - image_generator_service
    network_mode: host


  web_service:
    build: web_service/
    ports:
      - "5000:80"

  image_generator_service:
    build: image_generator_service/
    ports:
      - "5001:80"